# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ./a.out
email: rajeevs1992@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My personal blog, usually contains rants about my encounters
    with computers, with a once in a while dump of frustration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rajeevs.tk" # the base hostname & protocol for your site
twitter_username: rajeevs1992
github_username:  rajeevs1992

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
